[package]
name = "stdio"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
neovim = { path = "../../lib/" }
bytes = "*"
futures = "*"
tokio-io = "*"
tokio-proto = "*"
tokio-service = "*"
