[package]
name = "server"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
neovim = { path = "../../lib/" }
tokio-proto = "*"
tokio-service = "*"
tokio-core = "*"
tokio-io = "*"
futures = "*"
bytes = "*"
