[package]
name = "simple"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
msgpack-rpc = { path = "../../lib" }

futures = "*"
tokio-core = "*"
tokio-timer = "*"
serde = "*"
serde_derive = "*"
rmpv = { version = "*", features = ["with-serde"] }
