[package]
name = "msgpack-rpc"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
bytes = "*"
futures = "*"
tokio-core = "*"
tokio-io = "*"
tokio-proto = "*"
tokio-service = "*"
tokio-process = "*"

rmp = "*"
rmpv = "*"
